#公共配置
server:
    port: 80
    context-path : /isimPlatform
    tomcat:
      uri-encoding: UTF-8
spring:
  #redis配置
    #redis:
    #    database: 0
    #   host: 127.0.0.1
    #  port: 6379
    #    password:      # 密码（默认为空）
    #   timeout: 6000  # 连接超时时长（毫秒）
    #  pool:
    #    max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
    #    max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
    #    max-idle: 10      # 连接池中的最大空闲连接
  #    min-idle: 5       # 连接池中的最小空闲连接
  # 数据源配置
  datasource:
    url: jdbc:mysql://192.168.137.9:3306/fnpublic?useUnicode=true&characterEncoding=utf8&useSSL=false&tinyInt1isBit=true
    username: root
    password: fn@Passw0rd

#日志
logging:
  config: classpath:log/logback.xml
  path: /home/log/isim


#附件存放地址
remote :
  uploadPath : /opt/fnpublic/devFileUpload
  #获取应用发布状态
  getBCStatusURL : http://corepanel-s2i-test-corepanel.apps.cluster-244a.244a.sandbox1824.opentlc.com/getBCStatus






